# This is a hello world style GitHub shared workflow.
# See: https://docs.github.com/en/actions/using-workflows/reusing-workflows
#
# A shared workflow is a reusable, called workflow and may be shared a the
# Repository, Organization, or Enterprise level.
#
# A shared workflow is called by another workflow and accepts plain text
# inputs and encrypted secrets.

name: Send Greeting

on:
  workflow_call:
    inputs:
      greeting:
        type: string
        default: Hello world!
        description: The greeting text
        required: false
    secrets:
      do-not-tell:
        description: 'An secret value'
        required: true

jobs:
  scan:
    name: 'Greet'

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Speak Greeting
        run: echo "${{ inputs.greeting }}"
      - name: Whisper Secret
        run: echo "${{ secrets.do-not-tell }}"
